### ISSUE TITLE
implement the dosage class in whatever way seems fit

### ISSUE THREAD

**Issue by leojklarner** [SABS-Group-1/pkmodelling#13]

**Comment by leojklarner** [comment]
We currently have the assumption that we start with an initial concentration of 0 in all compartments (makes sense to me), we should either make it an input or point to it in the documentation

**Comment by ewawieczorek** [comment]
Implemented in protocol.py
Allows for continuous dosing over a specified time frame, instantaneous dosing at several time points or a mix of those
