### ISSUE TITLE
Add tests to test_solution.py

### ISSUE THREAD

**Issue by lewis-chinery** [SABS-Group-1/pkmodelling#17]
- [ ] Check that parameters of the wrong type raise TypeErrors e.g. strings used for the time range
- [ ] Check that parameters outside of the allowed range raise ValueErrors e.g. negative floats for the time range
---
- [ ] Check that the quantity of drug in all compartments is never negative
- [ ] Check that the total quantity of drug in all compartments is never greater than the total dose provided until that point
---
- [x] Check that we can solve for both IVB and SC models
- [x] Check that we can solve for any valid number of compartments
---
- [ ] Check that we can specify the time frame over which we want to solve
- [ ] Check that warnings are raised when the concentration in any one compartment exceeds the toxic threshold
- [ ] Check that warnings are raised when the concentration in any one compartment fails to meet the efficacy threshold

**Comment by leojklarner** [comment]
- [x] run solution with just the central compartment

- [x] run solution with basic IV / SC models

**Comment by leojklarner** [comment]
- [x] check for negative time/negative initial values
